"""phase8 shares prompts logs quota

Revision ID: 4925477d2735
Revises: 863177e7e6d3
Create Date: 2026-08-26 15:22:50.573738

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4925477d2735'
down_revision: Union[str, Sequence[str], None] = '863177e7e6d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('path', sa.String(length=400), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Integer(), nullable=False),
    sa.Column('error_code', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_logs_created_at'), 'request_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_request_logs_user_id'), 'request_logs', ['user_id'], unique=False)
    op.create_table('system_prompts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_prompts_workspace_id'), 'system_prompts', ['workspace_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('mode', sa.String(length=20), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_conversation_id'), 'shares', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_shares_token'), 'shares', ['token'], unique=True)
    op.create_index(op.f('ix_shares_user_id'), 'shares', ['user_id'], unique=False)
    op.add_column('user_settings', sa.Column('daily_message_limit', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('daily_token_limit', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('daily_image_limit', sa.Integer(), nullable=True))
    op.add_column('user_settings', sa.Column('daily_search_limit', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'daily_search_limit')
    op.drop_column('user_settings', 'daily_image_limit')
    op.drop_column('user_settings', 'daily_token_limit')
    op.drop_column('user_settings', 'daily_message_limit')
    pass  # created_at kept nullable
    op.drop_index(op.f('ix_shares_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_token'), table_name='shares')
    op.drop_index(op.f('ix_shares_conversation_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_system_prompts_workspace_id'), table_name='system_prompts')
    op.drop_table('system_prompts')
    op.drop_index(op.f('ix_request_logs_user_id'), table_name='request_logs')
    op.drop_index(op.f('ix_request_logs_created_at'), table_name='request_logs')
    op.drop_table('request_logs')
    # ### end Alembic commands ###
